branches:
  only:
  - master
  - develop
sudo: required
language: python
cache: pip
dist: bionic
python:
- '3.7'
services:
- docker
before_install:
- sudo apt-get update
- unzip -P infected tests/test_files.zip -d .
install:
- sudo docker-compose -f docker-compose-for-travis.yml build
- sudo docker-compose -f docker-compose-for-travis.yml up -d
script:
- sudo docker exec -ti intel_owl_uwsgi pip install flake8==3.8.4 black==20.8b1 coverage==5.3
- sudo docker exec -ti intel_owl_uwsgi black . --check
- sudo docker exec -ti intel_owl_uwsgi flake8 . --count
- sudo docker exec -ti intel_owl_uwsgi coverage run manage.py test tests
after_success:
  - bash <(curl -s https://codecov.io/bash)